テキストのモジュールを分けて見通しを良くしたよ。ただし......
myriko10/chocopy-easy pull request #28
Opened 2023-11-28 04:52 UTC by Yuki-Nakamura4

スコアに関してだけは表示する内容が静的じゃない(そのときのスコアの値を受け取って表示する)と思うんだけど書いててよく分らんくなったので一旦保留してそれ以外のタイトル、ゲームルール、ゲームオーバーらへんのテキスト設定だけ切り分けました。

2023-11-28 05:32 UTC, myriko10 requested changes
単に変更ではなくて増やしたファイルcheck_collisionとかの差分が表示されてるのが変だなあ。新しいmainをpullじゃなくてコピペで反映させてるわけではないよね？

2023-11-28 05:32 UTC, myriko10 commented on src/hurdle.py
18行目は必要なので生き返らせて

2023-11-28 05:32 UTC, myriko10 commented on src/main.py
> +    make_texts(WIDTH, HEIGHT)
上の方でやっているのでここではやらなくてよさそう

2023-11-28 05:32 UTC, myriko10 commented on src/text.py
> +    return (BASICFONT20, BASICFONT25, BASICFONT50,
returnで返さずに、main.pyに渡したいものはすべてtext.pyのグローバル変数として定義しておく？そうすると、from text import * でグローバル変数と関数がすべて使えるようになる。
インポート時の値で固定されてしまうなら問題だけど試してみてください。

2023-11-28 05:32 UTC, myriko10 commented on easy/src/main.py
これ消しておいて

2023-11-28 06:03 UTC, Yuki-Nakamura4 commented
pullしたときにマージエディター出て部分ごとに手動で確認・反映してるんだけどあんま勝手が分かってないのでおかしくなってそう――。直しときます

2023-11-29 01:18 UTC, myriko10 approved these changes

2023-11-29 01:23 UTC, merged