text.pyにscoreクラスをつくってスコアの更新と表示機能をmainから切り分けました
myriko10/chocopy-easy pull request #29
Opened 2023-11-29 08:04 UTC by Takum1Domon

スコア機能の切り分けできました

2023-12-01 02:19 UTC, myriko10 requested changes
モジュールを分ける、クラスが必須なのか検討する。

2023-12-01 02:19 UTC, myriko10 commented on src/text.py
スコアとテキストは別の機能なのでモジュール分けた方がいいと思いました。score.pyにtext.pyから必要なものをインポートでどうでしょうか。

2023-12-01 02:19 UTC, myriko10 commented on src/text.py
> +class Score:
わからないので検討してほしいこと。
クラス化は必須か？score.pyのグローバル変数にscoreを用意し、関数もクラスに含めずに記述するとどうなるか。

2023-12-01 07:02 UTC, Takum1Domon commented on src/text.py
了解修正します。
現状報告：textからインポートした変数が循環参照になってうまくいっていない

2023-12-01 07:06 UTC, Takum1Domon commented on src/text.py
> +class Score:
考えとしては
- グローバル変数を多用したくない。scoreは特に更新が多い変数なので
- ゲームオーバー後のリプレイを実装するときインスタンス生成するだけで済むからscoreを初期化する手間が省ける
ということでクラスにしました。

2023-12-04 02:21 UTC, myriko10 requested changes

2023-12-04 02:21 UTC, myriko10 commented on src/main.py
> -def score_calc(start_time):
動詞名詞の順番が一般的です。calcurate scoreなのでcalc_score 以下display scoreも同様。

2023-12-04 02:21 UTC, myriko10 commented on src/image_dict.py
../がなくなっているので自分の環境では実行できなくなっていました。main.pyをどこのディレクトリから実行するかでパスの表記を変更する必要があるみたいです。
chocopy-easy/src/にいるときにpython main.py で実行できるようにしておいてください。

2023-12-04 02:21 UTC, myriko10 commented on src/text.py
直しました。mainはtextを*インポートしていて、textはmainからWIDTHHIGHTをインポートしたいっていうことになっていて、python的にはどちらかをすすめるにはもう一方が決定されていないと進めないということに(印象はデッドロック)なっていたみたい。定数を別ファイルに分けて解消。

2023-12-04 08:10 UTC, myriko10 commented on src/score.py
> +    def score_update(self, is_game_over, start_time):
update_scoreにまた直そう。

2023-12-04 08:11 UTC, myriko10 approved these changes

2023-12-04 08:11 UTC, merged

2023-12-04 08:20 UTC, Takum1Domon commented on src/score.py
> +    def score_update(self, is_game_over, start_time):
確認不足でしたorz